# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.filename_listwidget = QtWidgets.QListWidget(self.centralwidget)
        self.filename_listwidget.setGeometry(QtCore.QRect(30, 60, 281, 621))
        self.filename_listwidget.setObjectName("filename_listwidget")
        self.imageDisplayer = QtWidgets.QLabel(self.centralwidget)
        self.imageDisplayer.setGeometry(QtCore.QRect(370, 60, 841, 611))
        self.imageDisplayer.setText("")
        self.imageDisplayer.setObjectName("imageDisplayer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_loadImage = QtWidgets.QAction(MainWindow)
        self.action_loadImage.setObjectName("action_loadImage")
        self.action_loadFolder = QtWidgets.QAction(MainWindow)
        self.action_loadFolder.setObjectName("action_loadFolder")
        self.menu.addAction(self.action_loadImage)
        self.menu.addAction(self.action_loadFolder)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "欲擴增檔案"))
        self.menu.setTitle(_translate("MainWindow", "檔案"))
        self.action_loadImage.setText(_translate("MainWindow", "載入圖片"))
        self.action_loadFolder.setText(_translate("MainWindow", "載入資料夾"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
